# Generated by Django 3.2.6 on 2021-08-12 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(max_length=200)),
                ('recieve_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Tint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tint_area', models.CharField(max_length=200)),
                ('tint_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TintTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now=True, verbose_name='time started')),
                ('finished_time', models.DateTimeField(blank=True, null=True, verbose_name='time finished')),
                ('car_tint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tint.car')),
                ('tint_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tint.tint')),
                ('tinter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
