# Generated by Django 3.2.6 on 2021-08-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinttask',
            name='finished_time',
            field=models.DateTimeField(blank=True, verbose_name='time finished'),
        ),
        migrations.AlterField(
            model_name='tinttask',
            name='start_time',
            field=models.DateTimeField(auto_now=True, verbose_name='time started'),
        ),
    ]
