# Generated by Django 3.2.6 on 2021-08-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tint', '0002_auto_20210811_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinttask',
            name='finished_time',
            field=models.DateTimeField(null=True, verbose_name='time finished'),
        ),
    ]
