# Generated by Django 3.2.6 on 2021-08-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tint', '0003_alter_tinttask_finished_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinttask',
            name='finished_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='time finished'),
        ),
    ]
